-   repo: https://github.com/awebdeveloper/pre-commit-prettier
    sha: '5f06a63'  # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        args: ['--write', '--no-semi', '--single-quote', '--trailing-comma', 'all']
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.8.0
    hooks:
      - id: trailing-whitespace
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: end-of-file-fixer
